version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: capitals_django
    volumes:
      - .:/app
    env_file:
      - ./.envs/django.env
    ports:
      - "8000:8000"

  server:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: capitals_django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    env_file:
      - ./.envs/django.env
    ports:
      - "8000:8000"
